#!/bin/bash

# LOGSTAR CONFIGURATION
export LOGSTAR_APIKEY=""
export LOGSTAR_GEODATA="True"
export LOGSTAR_DAYTIME="1"
export LOGSTAR_STARTDATE="2021-01-01"
export LOGSTAR_ENDDATE="2021-05-01"
export LOGSTAR_STATIONS=""

# database conf
export LOGSTAR_DB_USER="SA"
export LOGSTAR_DB_PASS="MyPassword!"
export LOGSTAR_DB_DBNAME="logstar"
export LOGSTAR_DB_DRIVER="ODBC Driver 17 for SQL Server"
export LOGSTAR_DB_PORT="1433"